# Docker Compose for local testing of the workshop application
version: '3.8'

services:
  # Backend API with DAPR (simulated)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DAPR_HTTP_PORT=3500
      - STATE_STORE_NAME=statestore
      - CORS_ORIGIN=http://localhost:3000,http://localhost:80
    volumes:
      - ./backend/src:/app/src
    networks:
      - workshop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - workshop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  workshop-network:
    driver: bridge

# Optional: Add Redis for DAPR state store simulation
# Uncomment if you want to test DAPR functionality locally
#  redis:
#    image: redis:7-alpine
#    ports:
#      - "6379:6379"
#    networks:
#      - workshop-network
